# Monthly Data Aggregation

## Data for property sold

In [43]:
import pandas as pd

sold1 = pd.read_csv("CRMLSSold202401.csv")
sold1
sold2 = pd.read_csv("CRMLSSold202402.csv")
sold2
sold3 = pd.read_csv("CRMLSSold202403.csv")
sold3
sold4 = pd.read_csv("CRMLSSold202404.csv")
sold4
sold5 = pd.read_csv("CRMLSSold202405_filled.csv")
sold5
sold6 = pd.read_csv("CRMLSSold202406_filled.csv")
sold6
sold7 = pd.read_csv("CRMLSSold202407_filled.csv")
sold7
sold8 = pd.read_csv("CRMLSSold202404.csv")
sold8
sold9 = pd.read_csv("CRMLSSold202409.csv")
sold9
sold10 = pd.read_csv("CRMLSSold202410.csv")
sold10
sold11 = pd.read_csv("CRMLSSold202411.csv")
sold11
sold12 = pd.read_csv("CRMLSSold202412.csv")
sold12
sold13 = pd.read_csv("CRMLSSold202501_filled.csv")
sold13
sold14 = pd.read_csv("CRMLSSold202502.csv")
sold14
sold15 = pd.read_csv("CRMLSSold202503.csv")
sold15
sold16 = pd.read_csv("CRMLSSold202504.csv")
sold16
sold17 = pd.read_csv("CRMLSSold202505.csv")
sold17
sold18 = pd.read_csv("CRMLSSold202506.csv")
sold18
sold19 = pd.read_csv("CRMLSSold202507.csv")
sold19
sold20 = pd.read_csv("CRMLSSold202508.csv")
sold20
sold21 = pd.read_csv("CRMLSSold202509.csv")
sold21
sold22 = pd.read_csv("CRMLSSold202510.csv")
sold22
sold23 = pd.read_csv("CRMLSSold202511.csv")
sold23
sold24 = pd.read_csv("CRMLSSold202512.csv")
sold24
sold25 = pd.read_csv("CRMLSSold202601.csv")
sold25
sold26 = pd.read_csv("CRMLSSold202602.csv")
sold26
sold27 = pd.read_csv("CRMLSSold202603.csv")
sold28 = pd.read_csv("CRMLSSold202604.csv")
sold28
sold29 = pd.read_csv("CRMLSSold202605.csv")
sold29
sold30 = pd.read_csv("CRMLSSold202606.csv")
sold30

/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/207672960.py:9: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold4 = pd.read_csv("CRMLSSold202404.csv")
/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/207672960.py:17: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold8 = pd.read_csv("CRMLSSold202404.csv")
/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/207672960.py:37: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  sold18 = pd.read_csv("CRMLSSold202506.csv")
/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/207672960.py:51: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold25 = pd.read_csv("CRMLSSold202601.csv")
/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/207672960.py:58: DtypeWarning: Columns (7,8,10,13,14,17,18,19,29,31,32,34,39,42,45,46,48,50,51,52,54,58,61,64,68,69,71,74,75,76) have mixed types. Specify dtype option on import or set low_memory=False.
  sold29 = pd.read_csv("CRMLSSold202605.csv")
/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/207672960.py:60: DtypeWarning: Columns (7,8,10,13,14,17,18,19,29,31,32,34,39,42,45,46,48,50,51,52,54,58,61,64,68,69,71,74,75,76) have mixed types. Specify dtype option on import or set low_memory=False.
  sold30 = pd.read_csv("CRMLSSold202606.csv")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    CRMLSSold202606
BuyerAgentAOR         ListAgentAOR          Flooring ViewYN WaterfrontYN BasementYN PoolPrivateYN OriginalListPrice ListingKey CloseDate  ClosePrice ListAgentFirstName ListAgentLastName Latitude     Longitude     UnparsedAddress                  PropertyType     LivingArea ListPrice DaysOnMarket ListOfficeName               BuyerOfficeName                            CoListOfficeName             ListAgentFullName CoListAgentFirstName CoListAgentLastName BuyerAgentMlsId BuyerAgentFirstName BuyerAgentLastName FireplacesTotal AssociationFeeFrequency AboveGradeFinishedArea ListingKeyNumeric MLSAreaMajor            TaxAnnualAmount CountyOrParish  MlsStatus ElementarySchool AttachedGarageYN ParkingTotal BuilderName PropertySubType       LotSizeAcres SubdivisionName   BuyerOfficeAOR        YearBuilt StreetNumberNumeric ListingId  BathroomsTotalInteger City           TaxYear BuildingAreaTotal BedroomsTotal ContractStatusChangeDate ElementarySchoolDistrict CoBuyerAgentFirstName PurchaseContractDate ListingContractDate BelowGradeFinishedArea BusinessType StateOrProvince CoveredSpaces MiddleOrJuniorSchool FireplaceYN Stories HighSchool Levels      LotSizeDimensions LotSizeArea MainLevelBedrooms NewConstructionYN GarageSpaces HighSchoolDistrict        PostalCode AssociationFee LotSizeSquareFeet MiddleOrJuniorSchoolDistrict OriginatingSystemName  OriginatingSystemSubName
BeverlyHillsGreaterLa BeverlyHillsGreaterLa NaN      FALSE  NaN          NaN        FALSE         1725000.0         1176695974 2026-06-25 1650000.0  Mimi               Gauriat           33.969105    -118.399725   8002 Dunfield Avenue             Residential      1887.0     1725000.0 0            Coldwell Banker Realty       Coldwell Banker Realty                     NaN                          Mimi Gauriat      NaN                  NaN                 CLW-C125952     Derrick             Smith              NaN             NaN                     NaN                    1176695974        C29 - Westchester       NaN             Los Angeles     Closed    NaN              NaN              0.0          NaN         SingleFamilyResidence 0.1865       NaN               BeverlyHillsGreaterLa 1952      8002                26857555   1                     Los Angeles    NaN     1887.0            2             2026-06-25               NaN                      NaN                   2026-06-08           2026-06-08          NaN                    NaN          CA              NaN           NaN                  FALSE       1       NaN        One         107x77            8122.0      NaN               FALSE             NaN          NaN                       90045      NaN            8122.0            NaN                          CRMLS                                  CRMLS_CL
Mlslistings           Mlslistings           NaN      FALSE  NaN          NaN        NaN           2480000.0         1176689433 2026-06-30 2480000.0  Lili               Chen              37.4941015   -122.24826475 1311 Central Avenue              Residential      1370.0     2480000.0 0            Coldwell Banker Realty       Coldwell Banker Realty                     NaN                          Lili Chen         NaN                  NaN                 ML5101271       Vicky               Yu                 NaN             NaN                     NaN                    1176689433        699 - Not Defined       NaN             San Mateo       Closed    NaN              TRUE             2.0          NaN         SingleFamilyResidence 0.1515       NaN               Mlslistings           1946      1311                ML82053521 1                     San Carlos     NaN     NaN               2             2026-06-30               NaN                      NaN                   2026-06-30           2026-06-30          NaN                    NaN          CA              NaN           NaN                  TRUE        NaN     NaN        NaN         NaN               6600.0      NaN               FALSE             2.0          Other                     94070      NaN            6600.0            NaN                          CRMLS                                CRMLS_MLSL
OrangeCounty          OrangeCounty          Tile     FALSE  NaN          NaN        FALSE         440000.0          1176674603 2026-06-25 440000.0   Jim                Holder            33.74004     -117.825755   655 W. 6th street A              Residential      1092.0     440000.0  0            Bullock Russell RE Services  Coldwell Banker Realty                     Bullock Russell RE Services  Jim Holder        Jonathan             Mesisca             settejon        Jonathan            Ettelson           NaN             Monthly                 NaN                    1176674603        71 - Tustin             NaN             Orange          Closed    NaN              NaN              1.0          NaN         Townhouse             NaN          Tustin Acres (TA) OrangeCounty          1963      655                 OC26060185 2                     Tustin         NaN     NaN               2             2026-06-25               NaN                      NaN                   2026-06-15           2026-03-18          NaN                    NaN          CA              NaN           NaN                  FALSE       2       NaN        Two         NaN               NaN         0                 FALSE             0.0          Tustin Unified            92780      450.0          NaN               NaN                          CRMLS                                 CRMLS_CRM
Mlslistings           Mlslistings           NaN      FALSE  NaN          NaN        NaN           NaN               1176638653 2026-06-22 8800000.0  NaN                The Dwyer Group   37.56829441  -122.3582419  30 Bayberry Place                Residential      5370.0     8800000.0 0            Compass                      Golden Gate Sotheby's International Realty NaN                           The Dwyer Group  NaN                  NaN                 ML5083304       Jenn                Gilson             NaN             NaN                     NaN                    1176638653        699 - Not Defined       NaN             San Mateo       Closed    NaN              TRUE             3.0          NaN         SingleFamilyResidence 0.5948       NaN               Mlslistings           1970      30                  ML82053405 6                     Hillsborough   NaN     NaN               6             2026-06-22               NaN                      NaN                   2026-06-22           2026-06-22          NaN                    NaN          CA              NaN           NaN                  TRUE        NaN     NaN        NaN         NaN               25908.0     NaN               FALSE             3.0          Other                     94010      NaN            25908.0           NaN                          CRMLS                                CRMLS_MLSL
...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ...
Southland             Southland             NaN      True   NaN          NaN        NaN           1400000.0         1022375158 2026-06-26 1215000.0  John               Murphy            34.659355   -118.252854    0 Vac/Cor Avenue L Pav /70th Stw Land             NaN        1400000.0 185          Re/Max All-Pro               Re/Max All-Pro                             NaN                          John Murphy       NaN                  NaN                 SR150560982     John                Murphy             NaN             NaN                     NaN                    1022375158        QHL - Quartz Hill       NaN             Los Angeles     Closed    NaN              NaN              NaN          NaN         NaN                   18.0754      NaN               Southland             NaN       0.0                 SR22193585 NaN                   Quartz Hill    NaN     NaN               NaN           2026-06-26               NaN                      NaN                   2023-03-06           2022-08-31          NaN                    NaN          CA              NaN           NaN                  NaN         NaN     NaN        NaN         NaN               787363.0    NaN               False             NaN          NaN                       93536      0.0            787363.0          NaN                          CRMLS                                 CRMLS_CRM
TheInlandGateway      TheInlandGateway      NaN      True   NaN          NaN        NaN           350000.0          1020936035 2026-06-15 200000.0   TONI               MARTINEZ          34.230699   -117.400935    1244 Knoll Street                Land             NaN        299999.0  1395         CENTURY 21 LOIS LAUER REALTY Town & Country Real Estate                 CENTURY 21 LOIS LAUER REALTY TONI MARTINEZ     Jake                 Bevens              EVRYANBUN       Ryan                Bunse              NaN             NaN                     NaN                    1020936035        274 - San Bernardino    NaN             San Bernardino  Closed    NaN              NaN              NaN          NaN         NaN                   2.8604       NaN               TheInlandGateway      NaN       1244.0              EV22167289 NaN                   San Bernardino NaN     NaN               NaN           2026-06-15               NaN                      NaN                   2026-05-27           2022-08-01          NaN                    NaN          CA              NaN           NaN                  NaN         NaN     NaN        NaN         NaN               124600.0    NaN               False             NaN          NaN                       92407      0.0            124600.0          NaN                          CRMLS                                 CRMLS_CRM
NorthSanLuisObispo    NorthSanLuisObispo    NaN      True   NaN          NaN        False         6989995.0         1014091927 2026-06-26 3000000.0  Billie Jo          Ralls             35.633015   -120.278054    3160 Gillis Canyon Road          Residential      1473.0     3800000.0 1553         RE/MAX Success               RE/MAX Success                             NaN                          Billie Jo Ralls   NaN                  NaN                 Prrallsb        Billie Jo           Ralls              NaN             NaN                     NaN                    1014091927        SHDN - Shandon          NaN             San Luis Obispo Closed    NaN              False            1.0          NaN         SingleFamilyResidence 2452.63      NaN               NorthSanLuisObispo    1948.0    3160.0              NS22033159 2.0                   Shandon        NaN     NaN               3.0           2026-06-26               NaN                      NaN                   2026-05-25           2022-02-21          NaN                    NaN          CA              NaN           NaN                  False       1.0     NaN        One         2452.63           2452.63     3.0               False             1.0          Paso Robles Joint Unified 93461      0.0            106836562.8       NaN                          CRMLS                                 CRMLS_CRM
SanDiego              SanDiego              NaN      False  NaN          NaN        False         2500.0            445312939  2026-06-23 4200.0     Nancy              Lozano            32.797003   -117.192107    3059 SUNSET CANYON               ResidentialLease 1451.0     4400.0    69           Nancy Lozano                 Nancy Lozano                               NaN                          Nancy Lozano      NaN                  NaN                 SAND-665519     Nancy               Lozano             NaN             NaN                     NaN                    445312939         92117 - Clairemont Mesa NaN             San Diego       Closed    NaN              True             2.0          NaN         Townhouse             NaN          Clairemont        SanDiego              2007.0    3059.0              150030236  4.0                   San Diego      NaN     NaN               3.0           2026-06-23               NaN                      NaN                   2026-06-23           2015-06-04          NaN                    NaN          CA              NaN           NaN                  False       NaN     NaN        ThreeOrMore NaN               NaN         NaN               NaN               2.0          NaN                       92117      0.0            NaN               NaN                          CRMLS                                CRMLS_SAND
Mrmls                 NorthSanDiegoCounty   NaN      NaN    NaN          NaN        NaN           5600.0            421654896  2026-06-26 3000.0     Lu Ann             Hall              33.138648   -117.180287    823 Grand Avenue 101-102         CommercialLease  NaN        3168.0    2614         Lu Ann Hall, Broker          None MRML                                  NaN                          Lu Ann Hall       NaN                  NaN                 NONE            NONE                NONE               NaN             NaN                     NaN                    421654896         92078 - San Marcos      NaN             San Diego       Closed    NaN              NaN              0.0          NaN         NaN                   NaN          NaN               Mrmls                 1990.0    823.0               160038805  0.0                   San Marcos     NaN     4550.0            NaN           2026-06-26               NaN                      NaN                   2026-06-23           2016-04-30          NaN                    NaN          CA              NaN           NaN                  NaN         NaN     NaN        NaN         NaN               NaN         NaN               NaN               NaN          NaN                       92078      0.0            NaN               NaN                          CRMLS                                 CRMLS_CRP

[25596 rows x 1 columns]

In [44]:
# Total sold rows before concatenation
before_sold = sum([
    len(sold1), len(sold2), len(sold3), len(sold4), len(sold5),
    len(sold6), len(sold7), len(sold8), len(sold9), len(sold10),
    len(sold11), len(sold12), len(sold13), len(sold14), len(sold15),
    len(sold16), len(sold17), len(sold18), len(sold19), len(sold20),
    len(sold21), len(sold22), len(sold23), len(sold24), len(sold25),
    len(sold26), len(sold27), len(sold28)
])


print("Rows sold before concatenation:", before_sold)

Rows sold before concatenation: 615807

In [45]:
#row count after concatenation for sold
after_sold = pd.concat([sold1, sold2,sold3, sold4,sold5, sold6,sold7, sold8,sold9, sold10,sold11, sold12,sold13, sold14,sold15, sold16,sold17, sold18,sold19, sold20,sold21, sold22,sold23, sold24,sold25, sold26,sold27, sold28])
print("Rows sold after concatenation:", len(after_sold))
after_sold

Rows sold after concatenation: 615807

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24256,SierraNorthValley,SierraNorthValley,NaN,True,NaN,NaN,NaN,200000.0,1014741959,dtownsendrealestate@gmail.com,...,95916,0.0,910839.6,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24257,SouthwestRiversideCounty,InlandValleys,NaN,True,NaN,NaN,NaN,97500.0,1002540286,scott@westcoe.com,...,92539,0.0,522720.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24258,Mrmls,Southland,NaN,True,NaN,NaN,NaN,15999.0,482785043,mr.khatibi@yahoo.com,...,93551,0.0,20009.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24259,OrangeCounty,HighDesert,NaN,True,NaN,NaN,NaN,6000000.0,446619807,jeffnyal@gmail.com,...,92882,NaN,122839.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24260,CitrusValley,CitrusValley,NaN,False,NaN,NaN,False,NaN,431883449,PABLOANS@AOL.COM,...,91709,NaN,21780.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

The number of rows are same before and after concatenation

In [46]:
## Number of rows before Residential filter for sold

print("number sold before residential filter:", len(after_sold))

number sold before residential filter: 615807

In [47]:
## Number of rows after Residential filter for sold
Residential_sold = after_sold[after_sold["PropertyType"] == "Residential" ]
Residential_sold
print("number sold after residential filter:", len(Residential_sold))

number sold after residential filter: 414567

## Data for property listed

All the listing dates

In [48]:
list3 = pd.read_csv("CRMLSListing202403.csv")
list3
list4 = pd.read_csv("CRMLSListing202404.csv")
list5 = pd.read_csv("CRMLSListing202405.csv")
list6 = pd.read_csv("CRMLSListing202406.csv")
list7 = pd.read_csv("CRMLSListing202407.csv")
list8 = pd.read_csv("CRMLSListing202408.csv")
list9 = pd.read_csv("CRMLSListing202409.csv")
list10 = pd.read_csv("CRMLSListing202410.csv")
list11 = pd.read_csv("CRMLSListing202411.csv")
list12 = pd.read_csv("CRMLSListing202412.csv")
list13 = pd.read_csv("CRMLSListing202501.csv")
list14 = pd.read_csv("CRMLSListing202502.csv")
list15 = pd.read_csv("CRMLSListing202503.csv")
list16 = pd.read_csv("CRMLSListing202504.csv")
list17 = pd.read_csv("CRMLSListing202505.csv")
list18 = pd.read_csv("CRMLSListing202506.csv")
list19 = pd.read_csv("CRMLSListing202507.csv")
list20 = pd.read_csv("CRMLSListing202508.csv")
list21 = pd.read_csv("CRMLSListing202509.csv")
list22 = pd.read_csv("CRMLSListing202510.csv")
list23 = pd.read_csv("CRMLSListing202511.csv")
list24 = pd.read_csv("CRMLSListing202512.csv")
list25 = pd.read_csv("CRMLSListing202601.csv")
list26 = pd.read_csv("CRMLSListing202602.csv")
list27 = pd.read_csv("CRMLSListing202603.csv")
list28 = pd.read_csv("CRMLSListing202604.csv")
list28
list29 = pd.read_csv("CRMLSListing202605.csv")
list29
list30 = pd.read_csv("CRMLSListing202606.csv")

/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/719758054.py:25: DtypeWarning: Columns (32,58,63,66) have mixed types. Specify dtype option on import or set low_memory=False.
  list26 = pd.read_csv("CRMLSListing202602.csv")
/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/719758054.py:29: DtypeWarning: Columns (0,1,3,6,7,10,11,12,22,24,25,27,34,37,40,41,42,43,45,47,48,49,51,52,56,58,59,61,64,70,71,73,77,78,79) have mixed types. Specify dtype option on import or set low_memory=False.
  list29 = pd.read_csv("CRMLSListing202605.csv")
/var/folders/gn/t0769g993173xwvtkqwcs0z80000gn/T/ipykernel_33886/719758054.py:31: DtypeWarning: Columns (0,1,3,6,7,10,11,12,22,24,25,27,34,37,40,41,42,43,45,47,48,49,51,52,56,58,59,61,64,70,71,73,77,78,79) have mixed types. Specify dtype option on import or set low_memory=False.
  list30 = pd.read_csv("CRMLSListing202606.csv")

In [49]:
# Total rows listed before concatenation
before_list = sum([
    len(list3), len(list4), len(list5), len(list6), len(list7),
    len(list8), len(list9), len(list10), len(list11), len(list12),
    len(list13), len(list14), len(list15), len(list16), len(list17),
    len(list18), len(list19), len(list20), len(list21), len(list22),
    len(list23), len(list24), len(list25), len(list26), len(list28),
])


print("Rows listed before concatenation:", before_list)

Rows listed before concatenation: 766844

In [50]:
# Total rows listed after concatenation
after_listing = pd.concat([
    list3, list4, list5, list6, list7, list8, list9, list10,
    list11, list12, list13, list14, list15, list16, list17,
    list18, list19, list20, list21, list22, list23, list24,
    list25, list26, list27, list28
], ignore_index=True)

print("Number of rows after concatenation:", len(after_listing))
after_listing

Number of rows after concatenation: 805997

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,2199.0,446830487,byui@pacbell.net,2024-04-19,2549.0,Brian,Yui,33.195473,-117.375439,202 S Nevada St. L,...,NaN,NaN,0.0,NaN,92054,HouseRebate.com,0.0,NaN,NaN,202 S Nevada St. L
1,3550000.0,1075011892,jasmineguo@firstteam.com,NaN,NaN,Meng,Guo,33.688369,-117.700659,100 Princess Pine,...,1.0,False,2.0,Irvine Unified,92618,NaN,295.0,5121.0,NaN,100 Princess Pine
2,1599000.0,1075010394,EK@ITZSOLD.COM,NaN,NaN,Edward,Kaminsky,33.886763,-118.371293,2217 Warfield Avenue,...,3.0,False,0.0,Redondo Unified,90278,NaN,0.0,6501.0,NaN,2217 Warfield Avenue
3,724999.0,1075001993,greg@sandiegodreamteam.com,NaN,NaN,Greg,Hill,32.777982,-117.041565,7200 Melody Lane 6,...,2.0,NaN,1.0,La Mesa-Spring Valley,91942,NaN,410.0,NaN,NaN,7200 Melody Lane 6
4,825000.0,1075001860,mikeaon@cox.net,2024-05-08,810000.0,Mike,Aon,32.713028,-117.095232,740 Cotton Street,...,4.0,False,0.0,San Diego Unified,92102,Coldwell Banker Royal Realty,0.0,11144.0,NaN,740 Cotton Street
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
805992,1375000.0,1151355330,ammarkosgroup@gmail.com,NaN,NaN,Athir,Markos,32.811131,-116.946359,1161 N Anza Street,...,NaN,NaN,NaN,NaN,92021,NaN,0.0,222156.0,NaN,1161 N Anza Street
805993,985000.0,1149517845,aisaethan@icloud.com,NaN,NaN,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,2.0,NaN,3.0,Lake Elsinore Unified,92530,NaN,0.0,14810.0,NaN,33115 Evergreen Sreet
805994,450000.0,1147219386,nathaly@shoppingsdhouses.com,NaN,NaN,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,NaN,NaN,0.0,Other,91977,NaN,510.0,91040.4,NaN,9860 Dale Avenue D2
805995,249000.0,1145273331,BillSoCalCoast@gmail.com,NaN,NaN,Bill,Church,33.229747,-117.127269,Little Canyon Lane,...,NaN,NaN,NaN,NaN,92026,NaN,210.0,37897.0,NaN,Little Canyon Lane
805996,1056400.0,1144232364,brokerosborne@gmail.com,2026-02-05,965200.0,John,Osborne,33.637915,-114.575821,9165 Intake Boulevard,...,NaN,NaN,NaN,NaN,92225,SimpliHOM,NaN,3445160.0,NaN,9165 Intake Boulevard

In [51]:
# number of rows of listed property before residentual filter
print("number listed before residential filter:", len(after_listing))

number listed before residential filter: 805997

In [52]:
# number of rows of listed property after residentual filter
Residential_list = after_listing[after_listing["PropertyType"] == "Residential" ]
Residential_list
print("number listed after residential filter:", len(Residential_list))

number listed after residential filter: 512665

In [53]:
Residential_list.to_csv("Residential_list.csv", index=False)

Residential_sold.to_csv("Residential_sold.csv", index=False)

# Week 2 IDX

In [54]:
# inspect structure
after_sold.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled'],
      dtype='object')

In [55]:
after_sold.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

In [56]:
after_sold.head(10)

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
5,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
6,SanDiego,SanDiego,"Carpet,Laminate,Tile",True,NaN,NaN,False,4200.0,518850317,nanloz@yahoo.com,...,91913,0.0,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
7,Laguna,Laguna,"Carpet,Tile",True,NaN,NaN,False,5500.0,518662094,Sydney@Agentsyd.com,...,92662,0.0,2590.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
8,HighDesert,HighDesert,NaN,True,NaN,NaN,NaN,3990.0,516546270,BrettB@GrandVistaRealty.com,...,96101,95.0,45738.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
9,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN

In [57]:
# Check property categories
after_sold['PropertyType'].unique()

array(['Residential', 'CommercialLease', 'Land', 'ResidentialLease',
       'ManufacturedInPark', 'ResidentialIncome', 'CommercialSale',
       'BusinessOpportunity'], dtype=object)

In [58]:
# Filter residential
after_sold = after_sold[after_sold.PropertyType == 'Residential']
after_sold

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
5,SanDiego,SanDiego,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
9,SanDiego,SanDiego,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,...,91950,NaN,NaN,NaN,CRMLS,CRMLS_SAND,NaN,NaN,NaN,NaN
28,Mlslistings,Mlslistings,NaN,False,NaN,NaN,NaN,NaN,1079166779,davidmartz@compass.com,...,92262,NaN,13504.0,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
29,Southland,Southland,NaN,False,NaN,NaN,False,1890500.0,1075037759,karen.klein@theagencyre.com,...,91356,0.0,17873.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24229,LakeCounty,LakeCounty,NaN,True,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,...,95424,0.0,10019.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24231,TheInlandGateway,TheInlandGateway,"Carpet,Tile,Wood",False,NaN,True,False,449000.0,1067010583,brian@cohen-realty.com,...,92322,0.0,12096.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24234,SanDiego,TriCounties,Vinyl,True,NaN,NaN,False,1579000.0,1063196193,info@homecoin.com,...,93619,0.0,859874.4,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24235,Mrmls,OrangeCounty,NaN,True,NaN,NaN,False,855000.0,1062106215,jefflachef@gmail.com,...,92629,0.0,2733.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
24242,Southland,PacificWest,"Carpet,Vinyl",False,NaN,NaN,False,375000.0,1052387780,elizabethoryan04@gmail.com,...,90302,345.0,23878.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN